functions:
  CronProcessor:
    name: DVSA-CRON-PROCESSOR
    handler: backend/src/functions/cronjobs/cron_processor.lambda_handler
    role: dvsaCronJobRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 30
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/cronjobs/cron_processor.py
    events:
    - schedule:
        name: daily_process_orders_status
        description: 'acts as an order proccess (daily change of order status... processed->shipped->delivered)'
        rate: rate(1 day)
        enabled: true

  CronOrderCleaner:
    name: DVSA-CRON-ORDER-CLEANER
    handler: backend/src/functions/cronjobs/cron_cleaner.lambda_handler
    role: dvsaCronJobRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 30
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/cronjobs/cron_cleaner.py
    events:
    - schedule:
        name: daily_clean_incomplete_orders
        description: 'clean all empty unpaid orders, once a day'
        rate: rate(1 day)
        enabled: true

  CronJobUpdate:
    name: DVSA-CRON-JOB-UPDATE
    handler: backend/src/functions/cronjobs/cron_update.lambda_handler
    role: dvsaCronJobRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 30
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/cronjobs/cron_update.py
    events:
    - schedule:
        name: daily_process_paid_orders
        description: 'creates a receipt for paid, unprocessed orders'
        rate: rate(1 day)
        enabled: true

resources:
  Resources:
    dvsaCronJobRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: dvsaCronJobRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
