
functions:
  OrderShipping:
    name: DVSA-ORDER-SHIPPING
    handler: backend/src/functions/order/order_shipping.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/order_shipping.py

  OrderBilling:
    name: DVSA-ORDER-BILLING
    handler: backend/src/functions/order/order_billing.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
      GET_CART_TOTAL: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.", {Ref: 'AWS::Region'}, ".amazonaws.com/${self:provider.stage}/total"]]}
      PAYMENT_PROCESS_URL: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.", {Ref: 'AWS::Region'}, ".amazonaws.com/${self:provider.stage}/payment"]]}
      SQS_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/dvsa-order-paid-sqs"
    timeout: 30
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/order_billing.py

  CancelOrder:
    name: DVSA-ORDER-CANCEL
    handler: backend/src/functions/order/cancel_order.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/cancel_order.py
  
  CompleteOrder:
    name: DVSA-ORDER-COMPLETE
    handler: backend/src/functions/order/order_complete.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
      INVENTORY_TABLE: DVSA-INVENTORY-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/order_complete.py

  GetOrder:
    name: DVSA-ORDER-GET
    handler: backend/src/functions/order/get_order.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/get_order.py

  OrderNew:
    name: DVSA-ORDER-NEW
    handler: backend/src/functions/order/new_order.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/new_order.py

  GetOrders:
    name: DVSA-ORDER-ORDERS
    handler: backend/src/functions/order/get_orders.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/get_orders.py
        
  OrderUpdate:
    name: DVSA-ORDER-UPDATE
    handler: backend/src/functions/order/update_order.lambda_handler
    role: dvsaOrdersRole
    environment:
      ORDERS_TABLE: DVSA-ORDERS-DB
    timeout: 10
    memorySize: 128
    package: 
      include: 
        - backend/src/functions/order/update_order.py

resources:
  Resources:
    dvsaOrdersRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: dvsaOrdersRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: dvsaOrdersRolePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: {'Fn::Join': [':', ['arn:aws:logs', {Ref: 'AWS::Region'}, {Ref: 'AWS::AccountId'}, 'log-group:/aws/lambda/*:*:*']]}
                - Effect: Allow
                  Action:
                    - dynamodb:*
                  Resource: {'Fn::Join': [':', ['arn:aws:dynamodb', {Ref: 'AWS::Region'}, {Ref: 'AWS::AccountId'}, 'table/*']]}
                - Effect: Allow
                  Action:
                    - sqs:*
                  Resource: {'Fn::Join': [':', ['arn:aws:sqs', {Ref: 'AWS::Region'}, {Ref: 'AWS::AccountId'}, 'dvsa-order-paid-sqs']]}